## DATA PREPROCESSING AND DATA CLEANING

In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('AIR_DATA.csv')
del df['StationId']
del df['Datetime']
df.head()

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,60.50,98.00,2.35,30.80,18.25,8.50,0.1,11.85,126.40,0.1,6.10,0.10,NaN,NaN
1,65.50,111.25,2.70,24.20,15.07,9.77,0.1,13.17,117.12,0.1,6.25,0.15,NaN,NaN
2,80.00,132.00,2.10,25.18,15.15,12.02,0.1,12.08,98.98,0.2,5.98,0.18,NaN,NaN
3,81.50,133.25,1.95,16.25,10.23,11.58,0.1,10.47,112.20,0.2,6.72,0.10,NaN,NaN
4,75.25,116.00,1.43,17.48,10.43,12.03,0.1,9.12,106.35,0.2,5.75,0.08,NaN,NaN

In [3]:
df.tail()

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
2589078,15.55,47.80,7.27,35.08,42.38,31.25,0.80,9.40,17.24,2.56,11.57,NaN,59.0,Satisfactory
2589079,15.23,42.30,6.10,26.78,32.85,30.66,0.56,4.91,17.46,3.49,12.29,NaN,59.0,Satisfactory
2589080,11.40,40.95,6.58,19.53,26.12,30.73,0.61,3.81,17.24,1.83,8.88,NaN,59.0,Satisfactory
2589081,9.25,34.33,9.17,21.85,31.00,29.61,0.65,3.44,12.74,1.40,8.43,NaN,59.0,Satisfactory
2589082,10.50,36.50,7.78,22.50,30.25,27.23,0.58,2.80,13.10,1.31,7.39,NaN,59.0,Satisfactory

In [4]:
df.shape

(2589083, 14)

In [5]:
df.size

36247162

In [6]:
df.columns

Index(['PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2', 'O3',
       'Benzene', 'Toluene', 'Xylene', 'AQI', 'AQI_Bucket'],
      dtype='object')

In [7]:
df['AQI_Bucket'].unique()

array([nan, 'Moderate', 'Poor', 'Very Poor', 'Satisfactory', 'Good',
       'Severe'], dtype=object)

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

var = ['AQI_Bucket']
  
for i in var:
    df[i] = le.fit_transform(df[i]).astype(int)

In [9]:
df.isnull()

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,False,False,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2589078,False,False,False,False,False,False,False,False,False,False,False,True,False,False
2589079,False,False,False,False,False,False,False,False,False,False,False,True,False,False
2589080,False,False,False,False,False,False,False,False,False,False,False,True,False,False
2589081,False,False,False,False,False,False,False,False,False,False,False,True,False,False
2589082,False,False,False,False,False,False,False,False,False,False,False,True,False,False

In [10]:
df = df.dropna()

In [11]:
df['AQI_Bucket'].unique()

array([1, 2, 5, 3, 0, 4])

In [12]:
df.describe()

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
count,203693.000000,203693.000000,203693.000000,203693.000000,203693.000000,203693.000000,203693.000000,203693.000000,203693.000000,203693.000000,203693.000000,203693.000000,203693.000000,203693.000000
mean,52.759292,109.395961,11.901996,33.645782,30.361168,17.330787,0.701461,9.783647,32.411483,4.533886,12.303780,2.843936,120.311042,1.834182
std,47.386817,76.704760,28.009370,27.180908,36.472885,15.206833,0.606331,11.230091,28.358028,14.570066,28.060733,10.035443,75.328235,1.279629
min,0.010000,1.000000,0.010000,0.010000,0.000000,0.010000,0.000000,0.010000,0.010000,0.000000,0.000000,0.000000,13.000000,0.000000
25%,24.000000,58.000000,1.600000,13.280000,11.100000,9.080000,0.350000,3.580000,12.200000,0.200000,1.110000,0.000000,72.000000,1.000000
50%,42.000000,94.000000,3.850000,26.480000,20.500000,13.620000,0.580000,6.700000,24.300000,1.300000,3.830000,0.620000,105.000000,1.000000
75%,69.000000,140.750000,10.040000,46.590000,35.470000,21.420000,0.890000,11.770000,43.650000,3.790000,11.880000,2.300000,139.000000,3.000000
max,999.990000,999.990000,497.300000,432.300000,499.200000,465.800000,48.520000,199.900000,199.920000,282.350000,499.050000,423.480000,818.000000,5.000000

In [13]:
df.corr()

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
PM2.5,1.000000,0.847882,0.350274,0.471717,0.460089,0.282144,0.482322,0.162077,-0.043815,0.118233,0.208731,0.119178,0.786344,0.277842
PM10,0.847882,1.000000,0.349677,0.507047,0.480890,0.273858,0.476773,0.195957,-0.050060,0.124158,0.217442,0.140978,0.757663,0.210436
NO,0.350274,0.349677,1.000000,0.334167,0.869167,0.121156,0.452428,0.012008,-0.182378,0.326802,0.268071,0.140198,0.288469,0.120880
NO2,0.471717,0.507047,0.334167,1.000000,0.661776,0.249797,0.435610,0.152927,-0.181512,0.124333,0.304510,0.227683,0.441733,0.101076
NOx,0.460089,0.480890,0.869167,0.661776,1.000000,0.206121,0.531523,0.057293,-0.222290,0.372315,0.346906,0.194476,0.426584,0.131101
NH3,0.282144,0.273858,0.121156,0.249797,0.206121,1.000000,0.163425,0.188046,-0.059098,0.073616,0.063883,0.029148,0.283593,0.118762
CO,0.482322,0.476773,0.452428,0.435610,0.531523,0.163425,1.000000,0.113498,-0.137411,0.198691,0.221141,0.162400,0.432508,0.141329
SO2,0.162077,0.195957,0.012008,0.152927,0.057293,0.188046,0.113498,1.000000,0.076843,-0.006602,0.107354,0.095866,0.135806,0.014627
O3,-0.043815,-0.050060,-0.182378,-0.181512,-0.222290,-0.059098,-0.137411,0.076843,1.000000,-0.110100,-0.121331,-0.074684,0.094589,-0.052093
Benzene,0.118233,0.124158,0.326802,0.124333,0.372315,0.073616,0.198691,-0.006602,-0.110100,1.000000,0.631691,0.146465,0.125644,-0.008713
Toluene,0.208731,0.217442,0.268071,0.304510,0.346906,0.063883,0.221141,0.107354,-0.121331,0.631691,1.000000,0.455891,0.169872,0.005758
Xylene,0.119178,0.140978,0.140198,0.227683,0.194476,0.029148,0.162400,0.095866,-0.074684,0.146465,0.455891,1.000000,0.090680,0.012687
AQI,0.786344,0.757663,0.288469,0.441733,0.426584,0.283593,0.432508,0.135806,0.094589,0.125644,0.169872,0.090680,1.000000,0.340889
AQI_Bucket,0.277842,0.210436,0.120880,0.101076,0.131101,0.118762,0.141329,0.014627,-0.052093,-0.008713,0.005758,0.012687,0.340889,1.000000

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 203693 entries, 16 to 2543908
Data columns (total 14 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   PM2.5       203693 non-null  float64
 1   PM10        203693 non-null  float64
 2   NO          203693 non-null  float64
 3   NO2         203693 non-null  float64
 4   NOx         203693 non-null  float64
 5   NH3         203693 non-null  float64
 6   CO          203693 non-null  float64
 7   SO2         203693 non-null  float64
 8   O3          203693 non-null  float64
 9   Benzene     203693 non-null  float64
 10  Toluene     203693 non-null  float64
 11  Xylene      203693 non-null  float64
 12  AQI         203693 non-null  float64
 13  AQI_Bucket  203693 non-null  int32
dtypes: float64(13), int32(1)
memory usage: 22.5 MB

In [15]:
pd.crosstab(df["PM2.5"], df["PM10"])

PM10,1.00,1.50,2.00,2.25,2.50,2.75,3.00,3.25,3.50,3.58,...,920.00,923.49,924.00,927.90,928.88,962.70,977.00,978.00,988.65,999.99
PM2.5,,,,,,,,,,,,,,,,,,,,,
0.01,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0.03,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0.04,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0.07,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0.10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
830.00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
830.40,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
887.00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
971.88,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999.99,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
df.groupby(["NO","NO2"]).groups

{(0.01, 3.5): [140471], (0.01, 5.03): [140822], (0.01, 6.62): [140642, 140785], (0.01, 6.92): [140910], (0.01, 7.99): [2528403], (0.01, 9.18): [135989], (0.01, 9.25): [1301358], (0.01, 9.35): [1301213], (0.01, 10.05): [1300329, 1301196], (0.01, 10.21): [1300205], (0.01, 11.0): [2528773], (0.01, 11.06): [1300087], (0.01, 11.17): [2528762], (0.01, 12.0): [1300174], (0.01, 12.15): [135676], (0.01, 12.18): [1299563], (0.01, 12.61): [1300698], (0.01, 13.31): [1300080], (0.01, 13.36): [1299279], (0.01, 13.61): [2520815], (0.01, 13.71): [1300152], (0.01, 14.28): [1299403], (0.01, 14.32): [1299222], (0.01, 14.59): [1299709], (0.01, 15.87): [1299637], (0.01, 17.54): [1300834], (0.01, 20.3): [137336], (0.02, 1.32): [2529301], (0.02, 2.87): [2529329], (0.02, 5.0): [140786], (0.02, 5.41): [140824], (0.02, 9.23): [1301227], (0.02, 10.12): [139784], (0.02, 11.99): [1299904], (0.02, 12.62): [1299751], (0.02, 14.26): [1300447], (0.02, 15.45): [1300768], (0.02, 19.72): [1298845], (0.02, 23.39): [2514399], (0.02, 24.35): [1298887], (0.03, 6.58): [140683], (0.03, 6.92): [2057453], (0.03, 8.45): [2057454], (0.03, 8.97): [1301228], (0.03, 9.23): [2057753], (0.03, 9.46): [1301361], (0.03, 9.99): [1301212], (0.03, 12.47): [2057513], (0.03, 13.02): [1300592], (0.03, 14.02): [1299687], (0.03, 14.12): [155], (0.03, 15.05): [136880], (0.03, 15.48): [1300344], (0.03, 16.25): [2057456], (0.03, 17.91): [1300477], (0.03, 22.99): [1300385], (0.03, 25.12): [2057052, 2528705], (0.04, 0.01): [128717], (0.04, 2.98): [2529205], (0.04, 5.38): [140665], (0.04, 5.44): [140682], (0.04, 5.96): [140933], (0.04, 8.45): [1902188], (0.04, 8.5): [1902210], (0.04, 8.52): [1902197], (0.04, 9.64): [137548], (0.04, 10.36): [1301178], (0.04, 13.12): [137191], (0.04, 13.73): [136060], (0.04, 14.61): [1301037], (0.04, 15.95): [2528515], (0.04, 20.08): [1299079], (0.04, 27.0): [1300739], (0.05, 1.85): [2056205], (0.05, 3.05): [2056202], (0.05, 5.6): [140908], (0.05, 6.07): [2057334], (0.05, 6.45): [2057778], (0.05, 6.75): [2057452], (0.05, 6.8): [2057766], (0.05, 7.75): [2057754], (0.05, 8.3): [1902164], (0.05, 8.37): [2057502], (0.05, 8.87): [2057683], (0.05, 10.55): [2057546], (0.05, 12.39): [1300261], (0.05, 12.68): [2057752], (0.05, 12.93): [1299689], (0.05, 13.14): [135677], (0.05, 13.55): [2057622], (0.05, 16.08): [2528547], (0.05, 19.68): [921], (0.05, 36.52): [2057748], (0.06, 4.02): [141029], (0.06, 5.86): [140878], (0.06, 7.05): [139878], (0.06, 9.05): [1301292], (0.06, 10.83): [1300332], (0.06, 12.23): [136876], (0.06, 13.13): [1299890], ...}

In [17]:
df["AQI_Bucket"].value_counts()

AQI_Bucket
1    88654
3    69531
0    22852
2    11704
5     9147
4     1805
Name: count, dtype: int64

In [18]:
pd.Categorical(df["NOx"]).describe()

            counts     freqs
categories
0.00            50  0.000245
0.01             2  0.000010
0.03             6  0.000029
0.04             2  0.000010
0.05            10  0.000049
...            ...       ...
496.50           1  0.000005
496.75           1  0.000005
497.70           1  0.000005
498.13           1  0.000005
499.20           1  0.000005

[14517 rows x 2 columns]

In [19]:
df.duplicated()

16         False
17         False
18         False
21         False
22         False
           ...
2543904    False
2543905    False
2543906    False
2543907    False
2543908    False
Length: 203693, dtype: bool

In [20]:
sum(df.duplicated())

16

In [21]:
df = df.drop_duplicates()

In [22]:
sum(df.duplicated())

0